<?php
declare(strict_types=1);

namespace SuzyEaston\LousyOutages;

/**
 * Canonical provider/source registry for Lousy Outages.
 */
class ProviderRegistry {
    public const DEFAULT_POLL_INTERVAL = 30 * MINUTE_IN_SECONDS;
    public const DEFAULT_FRESHNESS_THRESHOLD = 45 * MINUTE_IN_SECONDS;

    public static function all(): array {
        $providers = [
            ['id'=>'openai','name'=>'OpenAI','category'=>'ai','status_url'=>'https://status.openai.com/','source_type'=>'statuspage','source_endpoint'=>'https://status.openai.com/api/v2/summary.json','adapter'=>'statuspage_summary','enabled'=>true,'component_support'=>true,'maintenance_support'=>true,'history_support'=>true,'source_platform'=>'Atlassian Statuspage','content_type'=>'application/json','schema'=>'statuspage_summary','last_verified'=>'2026-07-21','source_notes'=>'Atlassian Statuspage summary API.'],
            ['id'=>'anthropic','name'=>'Claude / Anthropic','category'=>'ai','status_url'=>'https://status.claude.com/','source_type'=>'statuspage','source_endpoint'=>'https://status.claude.com/api/v2/summary.json','adapter'=>'statuspage_summary','enabled'=>true,'component_support'=>true,'maintenance_support'=>true,'history_support'=>true,'source_platform'=>'Atlassian Statuspage','content_type'=>'application/json','schema'=>'statuspage_summary','last_verified'=>'2026-07-21','source_notes'=>'Official Claude Statuspage summary API; unresolved incidents available at /api/v2/incidents/unresolved.json.'],
            ['id'=>'huggingface','name'=>'Hugging Face','category'=>'ai','status_url'=>'https://status.huggingface.co/','source_type'=>'better_stack','source_endpoint'=>'https://status.huggingface.co/index.json','adapter'=>'better_stack','enabled'=>true,'component_support'=>true,'maintenance_support'=>true,'history_support'=>true,'source_platform'=>'Better Stack','content_type'=>'application/json','schema'=>'better_stack_status_page_index','last_verified'=>'2026-07-21','source_notes'=>'Official Better Stack status page JSON. RSS candidate: https://status.huggingface.co/feed.rss.'],
            ['id'=>'mistral','name'=>'Mistral AI','category'=>'ai','status_url'=>'https://status.mistral.ai/','source_type'=>'checkly','source_endpoint'=>'','adapter'=>'none','enabled'=>false,'component_support'=>true,'maintenance_support'=>true,'history_support'=>false,'source_platform'=>'Checkly','content_type'=>'text/html','schema'=>'verification_delayed','last_verified'=>'2026-07-21','source_notes'=>'Checkly public page confirmed; stable anonymous structured endpoint not confirmed, so collection remains disabled.'],
            ['id'=>'cohere','name'=>'Cohere','category'=>'ai','status_url'=>'https://status.cohere.io/','source_type'=>'better_stack','source_endpoint'=>'https://status.cohere.io/index.json','adapter'=>'better_stack','enabled'=>true,'component_support'=>true,'maintenance_support'=>true,'history_support'=>true,'source_platform'=>'Better Stack','content_type'=>'application/json','schema'=>'better_stack_status_page_index','last_verified'=>'2026-07-21','source_notes'=>'status.cohere.io is the working Better Stack JSON source; status.cohere.com is retained as a redirect/canonical-page candidate only.'],
            ['id'=>'groq','name'=>'Groq','category'=>'ai','status_url'=>'https://groqstatus.com/','source_type'=>'candidate','source_endpoint'=>'','adapter'=>'none','enabled'=>false,'component_support'=>true,'maintenance_support'=>true,'history_support'=>false,'source_platform'=>'unknown','content_type'=>'text/html','schema'=>'verification_delayed','last_verified'=>'2026-07-21','source_notes'=>'Canonical public page found; stable anonymous structured endpoint not confirmed, so collection remains disabled.'],
            ['id'=>'replicate','name'=>'Replicate','category'=>'ai','status_url'=>'https://www.replicatestatus.com/','source_type'=>'candidate','source_endpoint'=>'','adapter'=>'none','enabled'=>false,'component_support'=>true,'maintenance_support'=>true,'history_support'=>false,'source_platform'=>'unknown','content_type'=>'text/html','schema'=>'verification_delayed','last_verified'=>'2026-07-21','source_notes'=>'Canonical public page found; stable anonymous structured endpoint not confirmed, so collection remains disabled.'],
            ['id'=>'elevenlabs','name'=>'ElevenLabs','category'=>'creative','status_url'=>'https://status.elevenlabs.io/','source_type'=>'candidate','source_endpoint'=>'','adapter'=>'none','enabled'=>false,'component_support'=>true,'maintenance_support'=>true,'history_support'=>false,'source_platform'=>'unknown','content_type'=>'text/html','schema'=>'verification_delayed','last_verified'=>'2026-07-21','source_notes'=>'Public page confirmed; no Statuspage summary API assumed until a stable structured source is verified.'],
            ['id'=>'github','name'=>'GitHub','category'=>'development','status_url'=>'https://www.githubstatus.com/','source_type'=>'statuspage','source_endpoint'=>'https://www.githubstatus.com/api/v2/summary.json','adapter'=>'statuspage_summary','enabled'=>true,'component_support'=>true,'maintenance_support'=>true,'history_support'=>true,'source_notes'=>'Official Statuspage summary API.'],
            ['id'=>'cloudflare','name'=>'Cloudflare','category'=>'cloud','status_url'=>'https://www.cloudflarestatus.com/','source_type'=>'statuspage','source_endpoint'=>'https://www.cloudflarestatus.com/api/v2/summary.json','adapter'=>'statuspage_summary','enabled'=>true,'component_support'=>true,'maintenance_support'=>true,'history_support'=>true,'source_notes'=>'Official Statuspage summary with status.json verification for empty degraded summaries.'],
            ['id'=>'aws','name'=>'AWS','category'=>'cloud','status_url'=>'https://health.aws.amazon.com/health/status','source_type'=>'rss','source_endpoint'=>'https://status.aws.amazon.com/rss/all.rss','adapter'=>'rss_atom','enabled'=>true,'component_support'=>false,'maintenance_support'=>true,'history_support'=>true,'source_notes'=>'Official AWS RSS; component/region extraction is conservative text metadata only.'],
            ['id'=>'azure','name'=>'Azure','category'=>'cloud','status_url'=>'https://azure.status.microsoft/','source_type'=>'rss','source_endpoint'=>'https://rssfeed.azure.status.microsoft/en-us/status/feed/','adapter'=>'rss_atom','enabled'=>true,'component_support'=>false,'maintenance_support'=>true,'history_support'=>true,'source_notes'=>'Official Microsoft Azure RSS feed.'],
            ['id'=>'google_cloud','name'=>'Google Cloud','category'=>'cloud','status_url'=>'https://status.cloud.google.com/','source_type'=>'gcp_json','source_endpoint'=>'https://status.cloud.google.com/incidents.json','adapter'=>'gcp_incidents_json','enabled'=>true,'component_support'=>true,'maintenance_support'=>false,'history_support'=>true,'source_notes'=>'Official Google Cloud incidents JSON.'],
            ['id'=>'google_workspace','name'=>'Google Workspace','category'=>'communications','status_url'=>'https://www.google.com/appsstatus/dashboard/','source_type'=>'rss','source_endpoint'=>'https://www.google.com/appsstatus/rss/en-CA','adapter'=>'rss_atom','enabled'=>true,'component_support'=>false,'maintenance_support'=>true,'history_support'=>true,'source_notes'=>'Official Google Workspace RSS feed.'],
            ['id'=>'slack','name'=>'Slack','category'=>'communications','status_url'=>'https://status.slack.com/','source_type'=>'slack_current','source_endpoint'=>'https://status.slack.com/api/v2.0.0/current','adapter'=>'slack_current','enabled'=>true,'component_support'=>true,'maintenance_support'=>true,'history_support'=>false,'source_notes'=>'Official Slack current-status API; history feed not used for current state.'],
            ['id'=>'atlassian','name'=>'Atlassian','category'=>'development','status_url'=>'https://status.atlassian.com/','source_type'=>'statuspage','source_endpoint'=>'https://status.atlassian.com/api/v2/summary.json','adapter'=>'statuspage_summary','enabled'=>true,'component_support'=>true,'maintenance_support'=>true,'history_support'=>true,'source_notes'=>'Official Statuspage summary API.'],
            ['id'=>'digitalocean','name'=>'DigitalOcean','category'=>'cloud','status_url'=>'https://status.digitalocean.com/','source_type'=>'statuspage','source_endpoint'=>'https://status.digitalocean.com/api/v2/summary.json','adapter'=>'statuspage_summary','enabled'=>true,'component_support'=>true,'maintenance_support'=>true,'history_support'=>true,'source_notes'=>'Official Statuspage summary API.'],
            ['id'=>'netlify','name'=>'Netlify','category'=>'development','status_url'=>'https://www.netlifystatus.com/','source_type'=>'statuspage','source_endpoint'=>'https://www.netlifystatus.com/api/v2/summary.json','adapter'=>'statuspage_summary','enabled'=>true,'component_support'=>true,'maintenance_support'=>true,'history_support'=>true,'source_notes'=>'Official Statuspage summary API.'],
            ['id'=>'vercel','name'=>'Vercel','category'=>'development','status_url'=>'https://www.vercel-status.com/','source_type'=>'statuspage','source_endpoint'=>'https://www.vercel-status.com/api/v2/summary.json','adapter'=>'statuspage_summary','enabled'=>true,'component_support'=>true,'maintenance_support'=>true,'history_support'=>true,'source_notes'=>'Official Statuspage summary API.'],
            ['id'=>'zoom','name'=>'Zoom','category'=>'communications','status_url'=>'https://status.zoom.us/','source_type'=>'statuspage','source_endpoint'=>'https://status.zoom.us/api/v2/summary.json','adapter'=>'statuspage_summary','enabled'=>true,'component_support'=>true,'maintenance_support'=>true,'history_support'=>true,'source_notes'=>'Official Statuspage summary API.'],
            ['id'=>'sentry','name'=>'Sentry','category'=>'development','status_url'=>'https://status.sentry.io/','source_type'=>'statuspage','source_endpoint'=>'https://status.sentry.io/api/v2/summary.json','adapter'=>'statuspage_summary','enabled'=>true,'component_support'=>true,'maintenance_support'=>true,'history_support'=>true,'source_notes'=>'Official Statuspage summary API.'],
            ['id'=>'teamviewer','name'=>'TeamViewer','category'=>'communications','status_url'=>'https://status.teamviewer.com/','source_type'=>'statuspage','source_endpoint'=>'https://status.teamviewer.com/api/v2/summary.json','adapter'=>'statuspage_summary','enabled'=>true,'component_support'=>true,'maintenance_support'=>true,'history_support'=>true,'source_notes'=>'Official Statuspage summary API.'],
            ['id'=>'zscaler','name'=>'Zscaler','category'=>'cloud','status_url'=>'https://trust.zscaler.com/zscaler.net/','source_type'=>'statuspage','source_endpoint'=>'https://status.zscaler.com/api/v2/summary.json','adapter'=>'statuspage_summary','enabled'=>true,'component_support'=>true,'maintenance_support'=>true,'history_support'=>true,'source_notes'=>'Official endpoint may return HTML; last-known-good is retained when available.'],
            ['id'=>'crowdstrike','name'=>'CrowdStrike','category'=>'cloud','status_url'=>'https://trust.crowdstrike.com/','source_type'=>'manual','source_endpoint'=>'','adapter'=>'manual','enabled'=>false,'component_support'=>false,'maintenance_support'=>false,'history_support'=>false,'source_notes'=>'Official public structured source not confirmed; retained as disabled manual candidate.'],
            ['id'=>'cursor','name'=>'Cursor','category'=>'ai','status_url'=>'https://status.cursor.com/','source_type'=>'candidate','source_endpoint'=>'','adapter'=>'none','enabled'=>false,'component_support'=>false,'maintenance_support'=>false,'history_support'=>false,'source_notes'=>'Candidate official page; structured endpoint not enabled until verified.'],
            ['id'=>'perplexity','name'=>'Perplexity','category'=>'ai','status_url'=>'https://status.perplexity.ai/','source_type'=>'candidate','source_endpoint'=>'','adapter'=>'none','enabled'=>false,'component_support'=>false,'maintenance_support'=>false,'history_support'=>false,'source_notes'=>'Candidate official page; structured endpoint not enabled until verified.'],
            ['id'=>'stability_ai','name'=>'Stability AI','category'=>'creative','status_url'=>'https://status.stability.ai/','source_type'=>'candidate','source_endpoint'=>'','adapter'=>'none','enabled'=>false,'component_support'=>false,'maintenance_support'=>false,'history_support'=>false,'source_notes'=>'Candidate official page; structured endpoint not enabled until verified.'],
            ['id'=>'runway','name'=>'Runway','category'=>'creative','status_url'=>'https://status.runwayml.com/','source_type'=>'candidate','source_endpoint'=>'','adapter'=>'none','enabled'=>false,'component_support'=>false,'maintenance_support'=>false,'history_support'=>false,'source_notes'=>'Candidate official page; structured endpoint not enabled until verified.'],
            ['id'=>'adobe','name'=>'Adobe Creative Cloud','category'=>'creative','status_url'=>'https://status.adobe.com/','source_type'=>'candidate','source_endpoint'=>'','adapter'=>'none','enabled'=>false,'component_support'=>false,'maintenance_support'=>false,'history_support'=>false,'source_notes'=>'Official status site exists, but no stable public structured source has been enabled.'],
            ['id'=>'google_gemini','name'=>'Google Gemini','category'=>'ai','status_url'=>'https://status.cloud.google.com/','source_type'=>'candidate','source_endpoint'=>'','adapter'=>'none','enabled'=>false,'component_support'=>false,'maintenance_support'=>false,'history_support'=>false,'source_notes'=>'Gemini-specific official structured status source not separately verified; Google Cloud remains enabled.'],
        ];
        return array_map([self::class, 'normalize'], $providers);
    }

    public static function enabled(): array { return array_values(array_filter(self::all(), static fn($p) => !empty($p['enabled']))); }
    public static function candidates(): array { return array_values(array_filter(self::all(), static fn($p) => empty($p['enabled']))); }

    private static function normalize(array $p): array {
        $p['type'] = $p['source_type'];
        $p['url'] = $p['source_endpoint'];
        $p['default_polling_interval'] = (int)($p['default_polling_interval'] ?? self::DEFAULT_POLL_INTERVAL);
        $p['freshness_threshold'] = (int)($p['freshness_threshold'] ?? self::DEFAULT_FRESHNESS_THRESHOLD);
        return $p;
    }
}
