<?php
declare(strict_types=1);

namespace SuzyEaston\LousyOutages\Sources;

use SuzyEaston\LousyOutages\SignalSourceInterface;

/** Optional Reddit source using official OAuth/API only; stores only safe counts/metadata. */
class RedditFieldReportsSource implements SignalSourceInterface {
    public function id(): string { return 'public_chatter_reddit'; }
    public function label(): string { return 'Reddit field reports'; }
    public function is_configured(): bool { return SourceRegistry::reddit_credentials_configured() && !empty(get_option('lousy_outages_public_chatter_reddit_enabled','0')); }
    public static function default_subreddits(): array { return ['sysadmin','aws','awscloud','cloudflare','googlecloud','OpenAI','ChatGPT','technology','vancouver','britishcolumbia','PersonalFinanceCanada','Rogers','bell','telus','toronto','canada']; }
    public static function configured_subreddits(): array { $raw=(string)get_option('lousy_outages_reddit_subreddits', implode("\n", array_map(static fn($s)=>'r/'.$s, self::default_subreddits()))); $subs=[]; foreach(preg_split('/[\r\n,]+/', $raw) ?: [] as $sub){ $sub=trim((string)$sub); $sub=preg_replace('#^https?://www\.reddit\.com/r/#i','',$sub); $sub=preg_replace('#^r/#i','',$sub); $sub=preg_replace('/[^A-Za-z0-9_]/','',$sub); if($sub!==''){$subs[]=$sub;} } return array_values(array_unique($subs)); }
    public function collect(array $options = []): array { $diag=['configured'=>$this->is_configured(),'attempted'=>false,'lane'=>'public_chatter','trust_level'=>'unconfirmed','capability'=>'official Reddit API/OAuth search','subreddits_configured'=>self::configured_subreddits(),'queries_attempted'=>0,'safe_summary_counts'=>[],'rows_stored'=>0,'watch_candidates'=>[],'skipped_reasons'=>[],'errors'=>[]]; if(!$diag['configured']){ $diag['skipped_reasons'][]='not_configured'; update_option('lo_diag_'.$this->id(),$diag,false); return []; } $token=$this->access_token($diag); if($token===''){ update_option('lo_diag_'.$this->id(),$diag,false); return []; } $queries=(array)($options['reddit_queries'] ?? ['outage OR down OR incident','aws outage OR cloudflare outage OR openai outage','rogers outage OR bell outage OR telus outage']); $subs=array_slice(self::configured_subreddits(),0,8); $out=[]; foreach(array_slice($queries,0,3) as $q){ foreach($subs as $sub){ $diag['attempted']=true; $diag['queries_attempted']++; $url='https://oauth.reddit.com/r/'.rawurlencode($sub).'/search?restrict_sr=1&sort=new&t=hour&limit=10&q='.rawurlencode((string)$q); $res=wp_remote_get($url,['timeout'=>8,'headers'=>['Authorization'=>'Bearer '.$token,'User-Agent'=>$this->ua()]]); if(is_wp_error($res)){ $diag['errors'][]='request_error'; continue; } $code=(int)wp_remote_retrieve_response_code($res); if($code>=400){ $diag['errors'][]='api_http_error_'.$code; continue; } $body=json_decode((string)wp_remote_retrieve_body($res),true); $children=(array)($body['data']['children']??[]); $count=count($children); $diag['safe_summary_counts'][$sub]=(int)($diag['safe_summary_counts'][$sub]??0)+$count; if($count>0){ $diag['watch_candidates'][]=['source'=>$this->id(),'subreddit'=>'r/'.$sub,'query_hash'=>hash('sha256',(string)$q),'count'=>$count,'reason'=>'metadata_only_no_public_text']; } } } $diag['rows_stored']=count($out); update_option('lo_diag_'.$this->id(),$diag,false); return $out; }
    private function ua(): string { return trim((string)get_option('lousy_outages_reddit_user_agent','LousyOutages/'.(defined('LOUSY_OUTAGES_VERSION')?LOUSY_OUTAGES_VERSION:'0.2.0').' by suzyeaston.ca')); }
    private function access_token(array &$diag): string { $cached=get_transient('lo_reddit_access_token'); if(is_string($cached)&&$cached!=='') return $cached; $id=trim((string)get_option('lousy_outages_reddit_client_id','')); $secret=trim((string)get_option('lousy_outages_reddit_client_secret','')); if($id===''||$secret===''){ $diag['skipped_reasons'][]='missing_credentials'; return ''; } $res=wp_remote_post('https://www.reddit.com/api/v1/access_token',['timeout'=>8,'headers'=>['Authorization'=>'Basic '.base64_encode($id.':'.$secret),'User-Agent'=>$this->ua()],'body'=>['grant_type'=>'client_credentials']]); if(is_wp_error($res)){ $diag['errors'][]='oauth_request_error'; return ''; } if((int)wp_remote_retrieve_response_code($res)>=400){ $diag['errors'][]='oauth_http_error'; return ''; } $body=json_decode((string)wp_remote_retrieve_body($res),true); $token=(string)($body['access_token']??''); if($token!==''){ set_transient('lo_reddit_access_token',$token,max(60,(int)($body['expires_in']??3600)-60)); } return $token; }
}
